import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren, ReactNode } from "react";
import { RouteProgress } from "@/components/shared/router-progress";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  modal: ReactNode;
};

export default function RootLayout({
  children,
  modal,
}: PropsWithChildren<Props>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RouteProgress />
        {children}
        {modal}
      </body>
    </html>
  );
}
